import type { Metadata } from "next";
import { Signika } from "next/font/google";
import "./globals.css";
import { Codecorner } from "./components/Codecorner";
import { GoogleAnalytics } from '@next/third-parties/google';
import { MatomoAnalytics } from "./components/MatomoAnalytics";

const signikaSans = Signika({
  weight: "600",
  subsets: ["latin"],
  variable: "--font-signika",
});

export const metadata: Metadata = {
  title: "Louísa's Linktree",
  description: "Generated by create next app",
};


export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta charSet="UTF-8" />
        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="darkreader-lock" />
        <link rel="me" href="https://mk.absturztau.be/@louisa_uno" />
        <GoogleAnalytics gaId="G-2HDHDD6XRF" />
        <MatomoAnalytics baseUrl="https://metrics.louisa.uno" siteId="1" />
      </head>
      <body className={signikaSans.className}>
        {children}
        <Codecorner />
      </body>
    </html>
  );
}
